version: "3.7"
services:
  order-service:
    image: dejmartins/order-service:latest
    container_name: 'order-service'
    restart: always
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://order-service:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - ORDER_QUEUE_URI=${ORDER_QUEUE_URI}
      - ORDER_QUEUE_HOSTNAME=${ORDER_QUEUE_HOSTNAME}
      - ORDER_QUEUE_USERNAME=${ORDER_QUEUE_USERNAME}
      - ORDER_QUEUE_PASSWORD=${ORDER_QUEUE_PASSWORD}
      - ORDER_QUEUE_NAME=${ORDER_QUEUE_NAME}
      - USE_WORKLOAD_IDENTITY_AUTH=${USE_WORKLOAD_IDENTITY_AUTH}
      - ORDER_DB_URI=${ORDER_DB_URI}
      - ORDER_DB_NAME=${ORDER_DB_NAME}
      - ORDER_DB_COLLECTION_NAME=${ORDER_DB_COLLECTION_NAME}
      - ORDER_QUEUE_PORT=${ORDER_QUEUE_PORT}
      - ORDER_QUEUE_TRANSPORT=${ORDER_QUEUE_TRANSPORT}
    networks:
      - backend_services

  product-service:
    image: dejmartins/product-service:latest
    container_name: 'product-service'
    restart: always
    ports:
      - 3002:3002
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://product-service:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services

networks:
  backend_services:
    driver: bridge
